version: "3.8"
services:
  slides:
    image: kubernetescourse/slides-docker
    build:
      context: ./slides
      dockerfile: ../Dockerfile
    volumes: 
      - ./slides:/usr/share/nginx/html
    ports:
      - 8081:80
