# syntax=docker/dockerfile:1

FROM ruby:3.0

RUN apt update && apt upgrade -y && \
    apt install -y vim && \
    apt clean && \
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    truncate -s 0 /var/log/*log

COPY ./blog /blog

WORKDIR /blog
RUN bundle install

CMD ["bin/rails", "s", "-b", "0.0.0.0"]